(()=>{const h=window.__highway,r=h.run,s=h.street;cancelAnimationFrame(r.raf);r.paused=false;r.chase=null;r.over=false;r.crashing=false;s.wanted=0;const out=[];const ok=(name,v,data)=>{out.push({name,pass:!!v,data});if(!v)throw Error(JSON.stringify(out))};
s.visit();ok('station built',s.stations.length===1&&s.parked.length===2);ok('rigged characters loaded',s.hero.ready&&s.npcs.every(n=>n.h.ready));s.interact();ok('exit car',s.onFoot);
const st=s.stations[0],point=(x,z)=>{const q=st.root.localToWorld(new s.T.Vector3(x,0,z));s.actor.x=q.x;s.actor.z=q.z;s.actor.s=st.s-z;s.actor.y=q.y;s.toRoad(q.x,q.z,s.actor.s,s.actor)};
point(54,0);s.actor.yaw=s.camYaw=Math.atan2(st.clerk.x-s.actor.x,-(st.clerk.z-s.actor.z));s.input.aim=true;s.input.use=true;for(let i=0;i<190;i++){r.elapsed+=1/60;s.update(1/60)}ok('robbery pays once',r.coinCount>=35&&s.cans===1&&s.snacks===2&&s.wanted===3,{coins:r.coinCount,cans:s.cans,snacks:s.snacks});for(let i=0;i<190;i++){r.elapsed+=1/60;s.update(1/60)}ok('robbery cooldown',s.cans===1);
s.input={};point(47.5,-6);s.interact();ok('snack looting',s.snacks===5);s.interact();ok('shelves cannot repeat',s.snacks===5);
point(22,0);s.interact();ok('fuel looting',s.cans===2);
const v=s.parked[0];r.player.place(r.player.s-60,8,0,0);s.actor.x=v.x+3;s.actor.z=v.z;s.actor.s=v.s;s.input={};s.interact();ok('walks to the door first',s.onFoot&&s.enter?.v===v);for(let i=0;i<500&&s.onFoot;i++){r.elapsed+=1/60;s.update(1/60)}ok('carjack transfers control',r.player===v&&!s.onFoot&&s.parked.includes(v)===false);ok('driver pulled out',s.npcs.some(n=>n.st.pseudo&&n.state==='down'));
v.vx=0;s.exitCar();const civ=s.npcs.find(n=>n.role==='civilian');s.actor.x=civ.x-1;s.actor.z=civ.z;s.actor.yaw=Math.PI/2;r.elapsed+=1;s.attack('left');r.elapsed+=1;s.attack('right');r.elapsed+=1;s.attack('left');ok('civilian knockdown',civ.state==='down');const civ2=s.npcs.find(n=>n.role==='civilian'&&n!==civ&&n.state!=='down');civ2.state='idle';civ2.health=100;s.actor.x=civ2.x-8;s.actor.z=civ2.z;s.toRoad(s.actor.x,s.actor.z,s.actor.s,s.actor);s.actor.y=civ2.y;s.weapon='pistol';s.ammo=12;s.aimRay.o.set(civ2.x-8,civ2.y+1.2,civ2.z);s.aimRay.d.set(1,0,0);s.input.aim=true;r.elapsed+=1;s.attack('shot');r.elapsed+=1;s.attack('shot');ok('pistol hits pedestrian',civ2.state==='down'&&s.ammo===10,{state:civ2.state,ammo:s.ammo});s.input={};const res0=s.reserve;s.reload();for(let i=0;i<90;i++){r.elapsed+=1/60;s.update(1/60)}ok('reload',s.ammo===12&&s.reserve===res0-2,{ammo:s.ammo,reserve:s.reserve});s.switchWeapon('fists');ok('weapon switch',s.weapon==='fists');s.switchWeapon('pistol');s.jump();let peak=0;for(let i=0;i<60;i++){r.elapsed+=1/60;s.update(1/60);peak=Math.max(peak,s.actor.lift)}ok('jump and land',peak>.4&&s.actor.lift===0,{peak});
const b=st.blocks.find(b=>b.kind==='crate'),q=st.root.localToWorld(new s.T.Vector3(b.x-1,0,b.z));v.x=q.x;v.z=q.z;v.s=st.s-b.z;v.vx=25;s.collide(v);ok('station collision breaks props',b.broken);
s.road.env.sea=true;v.s=400;let water;for(let d=-30;d>-220;d-=5){const w=s.worldFromRoad(v.s,d);if(s.isWater({...w,s:v.s})){water=w;break}}ok('water found',water);v.x=water.x;v.z=water.z;s.onFoot=false;s.update(1/60);ok('water stops car and starts swim',v.submerged&&s.onFoot&&s.actor.swimming,{speed:v.speed});v.input.throttle=1;v.step(1);ok('submerged engine disabled',v.speed===0);s.actor.stamina=0;s.actor.health=.1;s.update(.1);ok('drowning rescue',!s.actor.swimming&&s.actor.health===100&&!v.submerged);
point(45,0);s.firstPerson=true;s.updateCamera(.016);ok('first-person camera',s.camera.near===.08&&s.camera.fov===72);s.firstPerson=false;s.updateCamera(.016);
document.querySelectorAll('.street-presets button')[0].click();ok('easy preset',h.difficulty.level===0);document.querySelectorAll('.street-presets button')[1].click();ok('hard preset',h.difficulty.level===100);
s.wanted=0;r.chase=null;s.visit();s.exitCar();point(45,0);s.actor.yaw=Math.PI/2;s.update(.016);s.updateCamera(.016);h.parts.render();r.paused=true;s.hud();return JSON.stringify(out)})()
