(()=>{const h=window.__highway,r=h.run,s=h.street;cancelAnimationFrame(r.raf);r.paused=false;r.chase=null;r.over=false;r.crashing=false;s.wanted=0;const out=[];const ok=(name,v,data)=>{out.push({name,pass:!!v,data});if(!v)throw Error(JSON.stringify(out))};
s.visit();ok('station built',s.stations.length===1&&s.parked.length===2);s.interact();ok('exit car',s.onFoot);
const st=s.stations[0],point=(x,z)=>{const q=st.root.localToWorld(new s.T.Vector3(x,0,z));s.actor.x=q.x;s.actor.z=q.z;s.actor.s=st.s-z;s.actor.y=q.y;s.toRoad(q.x,q.z,s.actor.s,s.actor)};
point(54,0);s.actor.yaw=Math.atan2(st.clerk.x-s.actor.x,-(st.clerk.z-s.actor.z));s.input.aim=true;s.input.use=true;for(let i=0;i<190;i++){r.elapsed+=1/60;s.update(1/60)}ok('robbery pays once',r.coinCount>=35&&s.cans===1&&s.snacks===2&&s.wanted===3,{coins:r.coinCount,cans:s.cans,snacks:s.snacks});for(let i=0;i<190;i++){r.elapsed+=1/60;s.update(1/60)}ok('robbery cooldown',s.cans===1);
s.input={};point(47.5,-6);s.interact();ok('snack looting',s.snacks===5);s.interact();ok('shelves cannot repeat',s.snacks===5);
point(22,0);s.interact();ok('fuel looting',s.cans===2);
const v=s.parked[0];s.actor.x=v.x+3;s.actor.z=v.z;s.actor.s=v.s;s.actor.yaw=Math.atan2(v.x-s.actor.x,-(v.z-s.actor.z));s.input.aim=true;s.interact();ok('vehicle theft transfers control',r.player===v&&!s.onFoot&&s.parked.includes(v)===false);
v.vx=0;s.exitCar();const civ=s.npcs.find(n=>n.role==='civilian');s.actor.x=civ.x-1;s.actor.z=civ.z;s.actor.yaw=Math.PI/2;r.elapsed+=1;s.attack('left');r.elapsed+=1;s.attack('right');r.elapsed+=1;s.attack('left');ok('civilian knockdown',civ.state==='down');
const b=st.blocks.find(b=>b.kind==='crate'),q=st.root.localToWorld(new s.T.Vector3(b.x-1,0,b.z));v.x=q.x;v.z=q.z;v.s=st.s-b.z;v.vx=25;s.collide(v);ok('station collision breaks props',b.broken);
s.road.env.sea=true;v.s=400;let water;for(let d=-30;d>-220;d-=5){const w=s.worldFromRoad(v.s,d);if(s.isWater({...w,s:v.s})){water=w;break}}ok('water found',water);v.x=water.x;v.z=water.z;s.onFoot=false;s.update(1/60);ok('water stops car and starts swim',v.submerged&&s.onFoot&&s.actor.swimming,{speed:v.speed});v.input.throttle=1;v.step(1);ok('submerged engine disabled',v.speed===0);s.actor.stamina=0;s.actor.health=.1;s.update(.1);ok('drowning rescue',!s.actor.swimming&&s.actor.health===100&&!v.submerged);
point(45,0);s.firstPerson=true;s.updateCamera(.016);ok('first-person camera',s.camera.near===.08&&s.camera.fov===72);s.firstPerson=false;s.updateCamera(.016);
document.querySelectorAll('.street-presets button')[0].click();ok('easy preset',h.difficulty.level===0);document.querySelectorAll('.street-presets button')[1].click();ok('hard preset',h.difficulty.level===100);
s.wanted=0;r.chase=null;s.visit();s.exitCar();point(45,0);s.actor.yaw=Math.PI/2;s.update(.016);s.updateCamera(.016);h.parts.render();r.paused=true;s.hud();return JSON.stringify(out)})()
